클라이언트1, 클라이언트2가 서로의 위치 정보를 서버를 통해서 양방향 통신할 수 있게함.
bumsoft/Invaders-SDP-server pull request #1
Opened 2024-11-03 06:12 UTC by Kim-Mark

클라이언트의 'a,w,s,d'키 입력을 통해 위치 이동을 할 수 있으며 'a,w,s,d'키 입력이 들어왔을 때는 서버 내에서만 위치 정보를 최신화하고 클라이언트로부터 "GET" 요청이 들어오면 서버 내에서 최신화 된 위치 정보를 클라이언트에게 전송

=>Player 클래스에 플레이어의 위치좌표 x,y 명세
=> GameService 클래스에 movePlayer() 메소드 명세

2024-11-03 12:27 UTC, junghyun-coding approved these changes

2024-11-04 03:37 UTC, bumsoft requested changes
수정사항 반영 후, 
여러 유저의 접속을 처리할 수 있게 게임방에 대한 구현을 고려해보면 좋을 것 같음

2024-11-04 03:37 UTC, bumsoft commented on src/main/java/Invaders_SDP_server/GameWebSocketHandler.java
> +    GameService gameService;
private final로 되어야할 것 같습니다

2024-11-04 03:37 UTC, bumsoft commented on src/main/java/Invaders_SDP_server/GameWebSocketHandler.java
> +    public GameWebSocketHandler(GameService gameService) {
생성자 주입이 이뤄지지 않고있는 것 같습니다. Service Autowired애노테이션 이용필요

2024-11-04 03:37 UTC, bumsoft commented on src/main/java/Invaders_SDP_server/GameWebSocketHandler.java
> +                session2.sendMessage(new TextMessage(
GET요청을 한 클라이언트에게만 정보를 제공해주면 되기에, session2에게 전송하는 부분은 필요하지 않음

2024-11-04 03:37 UTC, bumsoft commented on src/main/java/Invaders_SDP_server/GameWebSocketHandler.java
> +                        String.format("x:%d,y:%d;enemy_x:%d,enemy_y:%d",
데이터가 많아진다면, 문자열 대신, json으로 보내는 게 더 좋을 것 같습니다.
jackson라이브러리의 ObjectMapper를 이용하면, DTO를 json형태로 전송할 수 있고, 클라이언트에서도 같은 dto를 사용해 쉽게 데이터를 받을 수 있습니다.
```
import com.fasterxml.jackson.databind.ObjectMapper;

private final ObjectMapper mapper;
session.sendMessage(new TextMessage(mapper.writeValueAsString(new GameResponseDTO(x1,y1, x2,y2))));
```

2024-11-04 16:05 UTC, bumsoft commented on src/main/java/Invaders_SDP_server/GameService.java
> +    Player player = new Player();
삭제

2024-11-19 08:10 UTC, closed without merging