유저관련 기능 추가
bumsoft/Invaders-SDP-server pull request #16
Opened 2024-11-19 08:12 UTC by bumsoft

기능추가 
- 회원가입 : 데이터베이스를 이용해 유저엔티티 저장 
- 로그인 : 스프링 시큐리티를 이용해 로그인 구현
- 랭킹 갱신 및 반환 : 클라이언트 요청시 랭킹 갱신 및 리스트 반환

2024-11-19 11:13 UTC, Kim-Mark commented on src/main/java/Invaders_SDP_server/SpringSecurity/SecurityConfig.java
>                          .anyRequest().permitAll())
관리자나 다른 권한 구분 없이 모든 요청을 인증 없이 허용하는 방법으로 하는 건가요?

2024-11-19 11:16 UTC, Kim-Mark commented on src/main/java/Invaders_SDP_server/SpringSecurity/SecurityConfig.java
> -                        .invalidateHttpSession(true)) //세션삭제
invalidateHttpSession, deleteCookies 중복 작업아님? 하나만 남겨놔도 괜찮을 듯?

2024-11-19 11:18 UTC, Kim-Mark reviewed
각 부분에 대한 Comment 검토 해주시면 감사하겠습니다

2024-11-19 11:46 UTC, ppk052 reviewed
그리고 롬복에 어노테이션으로 @Slf4j라는 로깅을 할수있는것이 있습니다. 이 어노테이션을 사용하면 log.info()로 로그를 남겨서 확인할수 있습니다.

2024-11-19 11:46 UTC, ppk052 commented on src/main/java/Invaders_SDP_server/SpringSecurity/SecurityConfig.java
우리가 유저의 개인정보를 저장하는 것이 아니기 때문에 스프링시큐리티를 쓸필요성은 없어보입니다. 시큐리티를 쓰게되면 그것에 대한 유지보수가 힘들어질것 같습니다.  클라이언트쪽에서 wallet저장하는것처럼 로그인했을때 유저 id(로그인id말고 primary_key입니다)를 로그인성공하면 저장했다가 게임을 끄거나 로그아웃할때 삭제하는걸로 하고 로그인 완료된 이후에는 서버에 방만들기 등의 요청을 보낼때 유저id(primary_key)만 보내는 것이 좋을것 같습니다.

2024-11-19 11:46 UTC, ppk052 commented on src/main/java/Invaders_SDP_server/User/UserRepository.java
보통 패키지를 controller, entity, dto, service, repository로 설정합니다. User폴더명을 Repository로 바꾸면 좋을것 같습니다!

2024-11-19 11:46 UTC, ppk052 commented on src/main/java/Invaders_SDP_server/User/dto/UserScoreDto.java
Dto에 보통 toEntity()라는 메서드를 사용하여 Dto를 entity로 바꿔줍니다. 그리고 Setter는 보안상 잘 사용하지 않습니다

2024-11-19 11:46 UTC, ppk052 commented on src/main/java/Invaders_SDP_server/User/service/UserService.java
> +    public List<UserScoreDto> getRanking()
반환형식이 List<UserScoreDto>인데 리파지토리에서 가져올때는 List<엔티티>로 받아옵니다

2024-11-19 11:48 UTC, ppk052 reviewed
롬복 어노테이션에서 Slf4j를 사용하면 log.info()로 로그를 남겨서 확인할 수 있습니다!

2024-11-19 11:49 UTC, ppk052 commented on src/main/java/Invaders_SDP_server/SpringSecurity/SecurityConfig.java
이거는 저의 의견이구 꼭 바꿔야 된다는 아닙니다!

2024-11-19 16:45 UTC, bumsoft commented
리뷰 반영했습니다! 확인 부탁드립니다

2024-11-20 05:40 UTC, ppk052 requested changes

2024-11-20 05:40 UTC, ppk052 commented on src/main/java/Invaders_SDP_server/User/repository/UserRepository.java
리파지토리는 entity만 주고받는데 List 구성요소로 UserScoreDto가 있는데 확인 부탁드립니다

2024-11-20 05:40 UTC, ppk052 commented on src/main/java/Invaders_SDP_server/User/dto/UserScoreDto.java
toEntity 메서드가 없습니다!

2024-11-20 06:44 UTC, bumsoft commented
User엔티티 setter사용부분 제거 후 생성자 및 메서드로 수정했습니다.

2024-11-20 12:02 UTC, ppk052 approved these changes
dto에서 엔티티로 바꾸는게 메서드가 안보입니다. 일단 작동에는 문제없다고 하셨고, 다음 스프린트 진행을 위해 통과시키겠습니다.

2024-11-20 12:02 UTC, ppk052 commented on src/main/java/Invaders_SDP_server/User/dto/Request_RegisterDto.java
dto를 엔티티로 만드는 메서드가 없는것 같습니다

2024-11-20 12:02 UTC, ppk052 commented on src/main/java/Invaders_SDP_server/User/dto/Response_UserScoreDto.java
dto를 엔티티로 만드는 메서드가 없는것 같습니다

2024-11-20 12:41 UTC, Kim-Mark approved these changes
Check

2024-11-20 12:53 UTC, merged